### ISSUE TITLE
after send image，  WARN PuppetLoginMixin logonoff() is deprecated, use `isLoggedIn` 

### ISSUE THREAD

**Issue by goldcome** [wechaty/puppet-wechat#171]
it also work ,but there is some errs
![微信截图_20211120111937](https://user-images.githubusercontent.com/2740261/142712992-e5c1d758-3cfc-4127-9bb8-c78a263353b5.png)

**Comment by huan** [comment]
Yes you are right, after inspecting the code, there have been some `selfId()` calls in the puppet wechat package.

This problem should have been fixed by the latest commit, and please try `wechaty-puppet-wechat@1.7.1` to see if it resolve the problem, and feel free to let me know the result.

**Comment by goldcome** [comment]
thank you, but there is some problems with npm install
```
npm ERR! notarget No matching version found for wechaty-puppet-wechat@1.7.1.
```
Have you published to npm?

**Comment by huan** [comment]
The v1.7.1 has failed some unit tests.

Please wait for the v1.7.2 to be published, you can see the result from the GitHub Actions at [here](https://github.com/wechaty/puppet-wechat/actions/runs/1483807512)

**Comment by goldcome** [comment]
@huan  it works without problem. thank you!

**Comment by huan** [comment]
You are welcome.

Please help us to close this issue if you have no future questions.
