### ISSUE TITLE
Can we get rid of UOS and use the original web protocol

### ISSUE THREAD

**Issue by hxianseng** [wechaty/puppet-wechat#193]
Now the UOS protocol cannot log in

**Comment by huan** [comment]
If we can confirm the UOS has problems and the original web protocol will be better, then we can use a options & environment variable to enable UOS, and disable UOS by default.

For example, the following names will be preferred:

1. `WECHATY_PUPPET_WECHAT_UOS=true` for the shell environment variable
2. `options.uos = true` for the puppet option.

I'd like to accept a PR based on that.

**Comment by henrycoding** [comment]
现在大多数web都封了

**Comment by hxianseng** [comment]
@ @

> 如果我们能确认UOS有问题，原来的web协议会更好，那么我们可以使用options&环境变量来开启UOS，默认关闭UOS。
> 
> 例如，以下名称将是首选：
> 
> 1. `WECHATY_PUPPET_WECHAT_UOS=true` 对于 shell 环境变量
> 2. `options.uos = true` 对于人偶选项。
> 
> 我想接受基于此的 PR。

This technology is used for the first time. How to turn off the UOS protocol
